Install Pandas Library

In [1]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

Install Numpy Library

In [2]:
pip install numpy

Requirement already satisfied: numpy in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.3.3)
Note: you may need to restart the kernel to use updated packages.

Import Pandas Library

In [3]:
import pandas as pd

Import Numpy Library

In [4]:
import numpy as np

Finding Missing Data

In [5]:
# Dictionary taiyar karein (5 records ke saath)
data_dict = {
    'ID': [1, 2, 3, 4, 5],
    'Name': ['Ali', 'Ahmed', 'Sara', 'Zain', 'Ayesha'],
    'City': ['Karachi', 'Lahore', 'Islamabad', 'Multan', 'Peshawar'],
    'Salary': [55000, 62000, np.nan, 48000, 51000], # Ek value missing (NaN) rakhi hai
    'Designation': ['Junior Dev', 'Backend Dev', 'Senior Dev', 'DevOps', 'Architect']
}
# Data ko table bana do
df = pd.DataFrame(data_dict)
# Table ko check karein
df

   ID    Name       City   Salary  Designation
0   1     Ali    Karachi  55000.0   Junior Dev
1   2   Ahmed     Lahore  62000.0  Backend Dev
2   3    Sara  Islamabad      NaN   Senior Dev
3   4    Zain     Multan  48000.0       DevOps
4   5  Ayesha   Peshawar  51000.0    Architect

In [6]:
# Har column mein kitni values missing hain
df.isnull().sum()

ID             0
Name           0
City           0
Salary         1
Designation    0
dtype: int64

Removing Missing Data

In [7]:
# Yeh function wo rows delete kar deta hai jahan koi bhi value missing (NaN) ho.
df.dropna()

   ID    Name      City   Salary  Designation
0   1     Ali   Karachi  55000.0   Junior Dev
1   2   Ahmed    Lahore  62000.0  Backend Dev
3   4    Zain    Multan  48000.0       DevOps
4   5  Ayesha  Peshawar  51000.0    Architect